name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test shapes
      id: test-shapes
      uses: education/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 60
        setup-command: sudo -H pip3 install pytest
    - name: test shape list
      id: test-shape-list
      uses: education/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 20
        setup-command: sudo -H pip3 install pytest
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        TEST-SHAPES_RESULTS: "${{steps.test-shapes.outputs.result}}"
        TEST-SHAPE-LIST_RESULTS: "${{steps.test-shape-list.outputs.result}}"
      with:
        runners: test-shapes,test-shape-list
